// This is a placeholder file. The actual sitemap is generated by src/app/sitemap.ts
// This file is required for Next.js to recognize the /sitemap.xml route.

import {NextResponse} from 'next/server';

export async function GET() {
  return new NextResponse('Sitemap will be generated dynamically.', {
    headers: {'Content-Type': 'text/plain'},
  });
}
